In [1]:
!pip install torch transformers tqdm pandas numpy librosa torchvision -q


[notice] A new release of pip is available: 23.3.1 -> 24.3.1
[notice] To update, run: python -m pip install --upgrade pip


In [3]:
import json
import re

import pandas as pd
import torch
from transformers import BertModel, BertTokenizer

In [6]:
from preprocessing.text import extract_bert_features, clean_str

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

input_file = 'transcriptions.csv'
output_file = "bert_features.jsonl"

df = pd.read_csv(input_file)
sentences = df["text"].apply(clean_str)
extract_bert_features(sentences, output_file)

cuda
Processed 8/1046 sentences
Processed 16/1046 sentences
Processed 24/1046 sentences
Processed 32/1046 sentences
Processed 40/1046 sentences
Processed 48/1046 sentences
Processed 56/1046 sentences
Processed 64/1046 sentences
Processed 72/1046 sentences
Processed 80/1046 sentences
Processed 88/1046 sentences
Processed 96/1046 sentences
Processed 104/1046 sentences
Processed 112/1046 sentences
Processed 120/1046 sentences
Processed 128/1046 sentences
Processed 136/1046 sentences
Processed 144/1046 sentences
Processed 152/1046 sentences
Processed 160/1046 sentences
Processed 168/1046 sentences
Processed 176/1046 sentences
Processed 184/1046 sentences
Processed 192/1046 sentences
Processed 200/1046 sentences
Processed 208/1046 sentences
Processed 216/1046 sentences
Processed 224/1046 sentences
Processed 232/1046 sentences
Processed 240/1046 sentences
Processed 248/1046 sentences
Processed 256/1046 sentences
Processed 264/1046 sentences
Processed 272/1046 sentences
Processed 280/1046 sen

In [1]:
from train import Config, SVMTrainer
from data_loader import DataLoader

In [2]:
config = Config()

In [3]:
data_loader = DataLoader(config)

In [49]:
trainer = SVMTrainer(config)

In [51]:
trainer.train_and_evaluate(data_loader)


Processing Fold 1

Confusion Matrix:
[[106  21]
 [ 41  42]]

Classification Report:
              precision    recall  f1-score   support

           0      0.721     0.835     0.774       127
           1      0.667     0.506     0.575        83

    accuracy                          0.705       210
   macro avg      0.694     0.670     0.675       210
weighted avg      0.700     0.705     0.695       210


Processing Fold 2

Confusion Matrix:
[[104  22]
 [ 43  40]]

Classification Report:
              precision    recall  f1-score   support

           0      0.707     0.825     0.762       126
           1      0.645     0.482     0.552        83

    accuracy                          0.689       209
   macro avg      0.676     0.654     0.657       209
weighted avg      0.683     0.689     0.678       209


Processing Fold 3

Confusion Matrix:
[[112  14]
 [ 41  42]]

Classification Report:
              precision    recall  f1-score   support

           0      0.732     0.889   